SELECT 1 AS ``
UNION ALL
SELECT 2 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 4 AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 7 AS ``
UNION ALL
SELECT 8 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 11 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 13 AS ``
UNION ALL
SELECT 14 AS ``
UNION ALL
SELECT 'FizzBuzz' AS ``
UNION ALL
SELECT 16 AS ``
UNION ALL
SELECT 17 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 19 AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 22 AS ``
UNION ALL
SELECT 23 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 26 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 28 AS ``
UNION ALL
SELECT 29 AS ``
UNION ALL
SELECT 'FizzBuzz' AS ``
UNION ALL
SELECT 31 AS ``
UNION ALL
SELECT 32 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 34 AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 37 AS ``
UNION ALL
SELECT 38 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 41 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 43 AS ``
UNION ALL
SELECT 44 AS ``
UNION ALL
SELECT 'FizzBuzz' AS ``
UNION ALL
SELECT 46 AS ``
UNION ALL
SELECT 47 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 49 AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 52 AS ``
UNION ALL
SELECT 53 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 56 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 58 AS ``
UNION ALL
SELECT 59 AS ``
UNION ALL
SELECT 'FizzBuzz' AS ``
UNION ALL
SELECT 61 AS ``
UNION ALL
SELECT 62 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 64 AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 67 AS ``
UNION ALL
SELECT 68 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 71 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 73 AS ``
UNION ALL
SELECT 74 AS ``
UNION ALL
SELECT 'FizzBuzz' AS ``
UNION ALL
SELECT 76 AS ``
UNION ALL
SELECT 77 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 79 AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 82 AS ``
UNION ALL
SELECT 83 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 86 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 88 AS ``
UNION ALL
SELECT 89 AS ``
UNION ALL
SELECT 'FizzBuzz' AS ``
UNION ALL
SELECT 91 AS ``
UNION ALL
SELECT 92 AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 94 AS ``
UNION ALL
SELECT 'Buzz' AS ``
UNION ALL
SELECT 'Fizz' AS ``
UNION ALL
SELECT 97 AS ``
UNION ALL
SELECT 98 AS ``
UNION ALL
SELECT 'Fizz' AS ``;