#!/bin/bash

# python
export PYTHONPATH=usr/local/lib/python2.7/site-packages:/Users/damian/Scripts/python
# PATH
export PATH=$PATH:"/Applications/microchip/xc16/v1.22/bin"

#  __  __ _          
# |  \/  (_)___  ___ 
# | |\/| | / __|/ __|
# | |  | | \__ \ (__ 
# |_|  |_|_|___/\___|
# 

shopt -s autocd # enable autocd
alias sqlite3="/usr/bin/sqlite3" # correct version of sqlite3
alias o="open ." # open cwd in finder
alias mate=subl  # subl is sublime text, symlinked: sudo ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/bin/subl
alias gpu="git push -u origin \`git rev-parse --abbrev-ref HEAD\`" # remote publish to matching branch

# unpack CORE stuff
function cpak() {
  RARS=`unzip -o \\*.zip | grep "inflating: .*\.rar" | cut -d' ' -f4 | tr '\n' ' '`
  unrar e -o+ `echo $RARS | cut -d' ' -f1` > /dev/null
  rm $RARS
}

# pipes stderr through cowsay
cow() { $* 2> >(cowsay 1>&2); }

alias sorry='sudo $(history -p !-1)'
alias fucking=sudo

# add cwd to ~/.paths, will be appended to PATH
appa() {
  if [ -z "$1" ]
    then echo `pwd` >> ~/.paths
  else 
    echo $1 >> ~/.paths
  fi
  source ~/.bashrc
}

export PATH=`cat ~/.paths | tr "\\n" ":"`$PATH

#     _              _           _     _ 
#    / \   _ __   __| |_ __ ___ (_) __| |
#   / _ \ | '_ \ / _` | '__/ _ \| |/ _` |
#  / ___ \| | | | (_| | | | (_) | | (_| |
# /_/   \_\_| |_|\__,_|_|  \___/|_|\__,_|
#

# vals
export FLPKG=io.trigger.forge633ed212c46d11e185cd12313d1adcbe
# PATH
export PATH="${PATH}:/android-ndk:/android-sdk/tools:/android-sdk/platform-tools:/android-sdk/gradle/wrapper"

# copy android resources
ANDROID_RES=/android-sdk/platforms/android-21/data/res
acpy() {
  find $1 -name $2 | cut -d'/' -f7,8 | xargs -L 1 -I % cp $1/% $3/%;
}

# record device screen screen
arec() {
  adb shell timeout -t $1 -s INT screenrecord /sdcard/tmp.mp4
  adb pull /sdcard/tmp.mp4
}

# copy android resources
ANDROID_RES=/android-sdk/platforms/android-21/data/res
acpy() {
  find $1 -name $2 | cut -d'/' -f7,8 | xargs -L 1 -I % cp $1/% $3/%;
}

# record screen for n seconds, e.g. `arec 6`
arec() {
  adb shell timeout -t $1 -s INT screenrecord /sdcard/tmp.mp4
  adb pull /sdcard/tmp.mp4
}

# start FarmLogs
alias fll='adb shell am start -n "$FLPKG/com.farmlogs.app.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER'

# builds and runs FarmLogs, e.g. `flb debug`
flb() {
  ./gradlew assemble$1
  adb install -r app/build/outputs/apk/app-$1.apk
  fll
}

# view/push database from device (requires sqlite viewer)
alias dbv="adb -d shell su -c 'cp /data/data/$FLPKG/databases/farmlogs.db /sdcard/farmlogs.db' && adb -d pull /sdcard/farmlogs.db ~/Desktop/farmlogs.db && open ~/Desktop/farmlogs.db"
alias dbp="adb -d push ~/Desktop/farmlogs.db /sdcard/farmlogs.db && adb -d shell am force-stop $FLPKG && adb -d shell su -c 'cp /sdcard/farmlogs.db /data/data/$FLPKG/databases/farmlogs.db'"

# view/push database from emulator
alias dbve="adb -e pull /data/data/$FLPKG/databases/farmlogs.db ~/Desktop/farmlogs.db && open ~/Desktop/farmlogs.db"
alias dbpe="adb -e shell am force-stop $FLPKG && adb -e push ~/Desktop/farmlogs.db /data/data/$FLPKG/databases/farmlogs.db"
